name: habit_tracker
description: A simple habit tracking app with streaks and rewards
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # state management
  provider: ^6.1.1
  
  # local storage
  shared_preferences: ^2.2.2
  
  # animations
  confetti: ^0.7.0
  animated_text_kit: ^4.2.2
  
  # icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true